In [376]:
import numpy as np 
from scipy.optimize import optimize 

In [377]:
LOWER_BOUND = -50
UPPER_BOUND = 50
NUMBER_SUBPOPULATION = 2
NUMBER_TASK = 2
DIMENSIONS = 5
np.random.seed(1)

In [378]:
class sphere_function:
    def __init__(self, dimension):
        self.dimension= dimension 
    def decode(self, array_value):
        array_value = array_value[:self.dimension]
        return array_value 
    def calculate_fitness(self,array_value):
        x = self.decode(array_value)
        # print(array_value.shape)
        # print(array_va)
        sum = np.sum(x * x, keepdims= True)
        return float(sum) 

In [379]:
class rastrigin_function: 
    def __init__(self, dimension, A = 10): 
        self.dimension = dimension
        self.A = A
    def decode(self, array_value):
        array_value = array_value[:self.dimension]
        return np.array(array_value)
    def calculate_fitness(self, array_value): 
        x = self.decode(array_value) 
        sum = self.A * self.dimension + np.sum(x * x) - self.A * np.sum(np.cos(2 * np.pi * np.cos(x)))
        return float(sum) 
 
        

In [380]:
population = np.zeros((NUMBER_SUBPOPULATION * NUMBER_TASK, DIMENSIONS))
skill_factor = np.zeros((1,NUMBER_SUBPOPULATION * NUMBER_TASK))
RMP = np.zeros((NUMBER_TASK, NUMBER_TASK))
factorial_cost = np.zeros((1,NUMBER_SUBPOPULATION * NUMBER_TASK))

tasks = [sphere_function(dimension= 2), rastrigin_function(dimension= 2)]

In [381]:
def evaluate_population(population, skill_factor, factorial_cost, tasks):
    for individual in range(len(population)):
        best_task = individual % NUMBER_TASK
        skill_factor[0][individual] =  best_task
        factorial_cost[0][individual] = (tasks[best_task].calculate_fitness(population[individual]))

In [382]:
def create_population(population):
    population = np.random.uniform(low = LOWER_BOUND, high = UPPER_BOUND, size= population.shape)

In [383]:
def compute_scalarfitness(factorial_cost, skill_factor):

    temp = np.empty_like(factorial_cost) 
    index = np.zeros((NUMBER_TASK, 1), dtype=int);
    
    for i in range(len(factorial_cost)):
        temp[skill_factor[i] * NUMBER_SUBPOPULATION + int(index[skill_factor[i]])] = factorial_cost[i]
        index[skill_factor[i]] += 1

    temp = np.array(temp) 
    ranks = np.empty_like(temp)

    for task in range(NUMBER_TASK): 
        temp2 = temp[task * NUMBER_TASK: (task+1) * NUMBER_TASK].argsort() 
        ranks[temp2 + task * NUMBER_TASK] = np.arange(len(temp2))

    real_ranks = np.zeros(temp.shape, dtype = float)
    index = np.zeros((NUMBER_TASK, 1), dtype=int);

    for i in range(len(factorial_cost)):
        real_ranks[i] = 1.0/(ranks[skill_factor[i] * NUMBER_SUBPOPULATION + index[skill_factor[i]]] + 1)
        index[skill_factor[i]] += 1
    print(real_ranks)
        
    

In [384]:
array = np.array([4,2,7,2])
temp = array.argsort()
print(temp)
ranks = np.empty_like(temp)
ranks[temp] = np.arange(len(array))
print(np.arange(3))
print(ranks)

[1 3 0 2]
[0 1 2]
[2 0 3 1]


In [385]:
a = np.array([[1,2,3],[3,4,5],[6,7,8]], dtype = float)
print(a.shape)
print(np.mean(a, axis = 0, dtype = float, keepdims= True))
print(np.std(a, axis = 0, dtype = float, keepdims= True))

(3, 3)
[[3.33333333 4.33333333 5.33333333]]
[[2.05480467 2.05480467 2.05480467]]


In [386]:
create_population(population)
evaluate_population(population, skill_factor, factorial_cost,tasks) 
compute_scalarfitness(factorial_cost, skill_factor)

IndexError: arrays used as indices must be of integer (or boolean) type