In [1]:
import numpy as np 

i = np.random.choice(np.arange(10)[1:], size= 1)
print(i)

[7]


In [14]:
from utils.operators import sbx_crossover 

a = np.array([0.4000004, 0.3, 0.2])
b = np.array([0.4000002, 0.2, 0.1])
oa, ob = sbx_crossover(a, b, swap= False)
print(oa)
print(ob)

[0.67405987 1.10365725 0.53459924]
[0.40000037 0.30518286 0.17672996]
[0.40000023 0.19481714 0.12327004]


In [114]:
a = 0.0901631786405019
b = 0.49999999999999999
import numpy as np 

print(np.log10(np.std(np.array([a,b]))))
print(a + np.random.normal(loc= 0, scale= 1e-2))
print(a)

-0.6884190211135358
0.09803742866701334
0.0901631786405019


In [1]:
import numpy as np 
a = np.ones(shape= (3, 3), dtype= int) 
a[:,1] = 0
a

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [35]:
import numpy as np 

a = np.array([3,4])
b = np.random.choice(a, size= 2, replace= True)
print(b)

[4 3]


In [1]:
from utils.operators import sbx_crossover 
a = np.zeros(shape= (9,)) + 0.9000000000000001
b = np.zeros(shape= (9,)) + 0.9000000000000001
print(a)
oa, ob = sbx_crossover(a, b)
print(oa)
print(ob)
print(a[0])
print(oa[0])

NameError: name 'np' is not defined

In [12]:
import numpy as np 

a = np.zeros(shape= (18,))
for i in range(18): 
    a[i] = i * 100 + 1
print(a)
a = 1/ a 
print(a) 
a = a / np.sum(a) 
print(a) 

[1.000e+00 1.010e+02 2.010e+02 3.010e+02 4.010e+02 5.010e+02 6.010e+02
 7.010e+02 8.010e+02 9.010e+02 1.001e+03 1.101e+03 1.201e+03 1.301e+03
 1.401e+03 1.501e+03 1.601e+03 1.701e+03]
[1.00000000e+00 9.90099010e-03 4.97512438e-03 3.32225914e-03
 2.49376559e-03 1.99600798e-03 1.66389351e-03 1.42653352e-03
 1.24843945e-03 1.10987791e-03 9.99000999e-04 9.08265213e-04
 8.32639467e-04 7.68639508e-04 7.13775874e-04 6.66222518e-04
 6.24609619e-04 5.87889477e-04]
[9.66895496e-01 9.57322273e-03 4.81042535e-03 3.21227739e-03
 2.41121071e-03 1.92993113e-03 1.60881114e-03 1.37930884e-03
 1.20711048e-03 1.07313596e-03 9.65929566e-04 8.78197544e-04
 8.05075350e-04 7.43194078e-04 6.90146678e-04 6.44167552e-04
 6.03932227e-04 5.68427687e-04]


In [2]:
import numpy as np 
for i in range(10):
    print(np.random.normal(loc= 0, scale= 10**-1))

0.11719069559123785
0.02066858340161395
-0.0015643336983793374
0.12204348335400267
0.2504904815115049
-0.07340047271399162
-0.039090322590278316
0.05955189934533181
0.05255764549168678
0.2854787400554212


In [7]:
import numpy as np 
a = 0.49999999999999994
while np.abs(a - 0.5) >=1e-25:
    a = 0.49999999999999994
    scale =10 **  (-int(np.random.choice(np.arange(17) + 1, size= 1)))
    
    a = np.random.normal(loc= a,scale= scale)
    print(a) 


0.49999999999999994
0.5611978754492872
0.5000000000000019
0.5000000033678653
0.4999999998988497
0.49990649633201645
0.5013126245909889
0.499999860812978
0.4999971987763637
0.5002251572492707
0.5000000178254835
0.4999998953407977
0.49999999994022915
0.5000005378540019
0.4999999999999999
0.49999999999999994
0.5000000000000011
0.49999999999999767
0.4999999993989829
0.4999923445730857
0.4999999978248222
0.49999999090960157
0.5000000115869686
0.4997221136970067
0.4999902347741674
0.49999992091183554
0.5000000000104361
0.5000007930365031
0.48527641084910617
0.4999615110654732
0.5001832859888345
0.49999999999999994
0.5000000000000282
0.49999931384657387
0.4987265158087481
0.4999114821668799
0.5106156341171594
0.49995901751864347
0.4999999999996133
0.5000000004856034
0.5000097913764514
0.5000000007148258
0.4999911920907954
0.5000011217826984
0.4997478421138117
0.4946517429126046
0.49999998184067973
0.5002178953012784
0.4981642963952938
0.499656280643789
0.5090355891437754
0.5000000087984775
0.

In [14]:
import numpy as np

a = np.array([0.100000, 0.100000, 0.1, 0.1]) 
print(np.mean(a))
print(np.std(a))
print(np.random.normal(np.mean(a), np.std(a)))
# b = 0
# count = 0 

# while count < 10:
#     count += 1
#     b = np.random.normal(loc= 0, scale= 0.00002)
#     print(b)
# print(0.00002 - 2e-5)


b = np.log10(1.2)
c = np.arange(int(np.abs(b)))
print(b)
print(c)
e = -10 
b = 10 ** e 
print(b) 

0.1
0.0
0.1
0.07918124604762482
[]
1e-10


In [2]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
np.random.shuffle(a)
print(a[:int(len(a)/2)])

[3, 6, 7, 5]


In [9]:
from utils.utils_model_mfea import * 
from utils.utils_gauss_adapt import * 
x = np.array([[1,2,3], [4,5,6], [3,4,5]])
y = add_coefficient_gauss(x) 
print(y)

[[ 1.          2.          3.          0.04183027]
 [ 4.          5.          6.         -0.10082062]
 [ 3.          4.          5.         -0.05443306]]


In [4]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8])
b = np.where(a > 4)
# np.where(a[a] < 8)
print(a[b])
np.where(a[b] < 8, b, None)

[5 6 7 8]


array([[4, 5, 6, None]], dtype=object)

In [5]:
balloon_tip("aa", "aa")

NameError: name 'balloon_tip' is not defined

In [ ]:
import numpy as np 

x = [1.0, 1.0, 0.5, 0.3, 1.0]
y = [1, 2, 1, 2, 3]

print(list(set(np.where(np.array(x) == 1)[0])&set(np.where(np.array(y) == 1)[0])))

print(np.

In [ ]:
import numpy as np 
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[0.1], [0.2]])

a = np.append(x, y, axis= 1)
print(a)

from utils.

[[1.  2.  3.  0.1]
 [4.  5.  6.  0.2]]


In [ ]:
class test():

    def __init__(self):
        self.arr = []
        pass
    def append(self, val):
        self.arr.append(val)

In [ ]:
mem = [test() for i in range(3)]

In [ ]:
mem[0].append(3)
mem[0].arr

In [ ]:
[mem[i].arr for i in range(3)]

In [ ]:


def push_notification(title= "Thông báo", content = "Chương trình của bạn đã xong"):
    from win10toast import ToastNotifier
    infor = ToastNotifier() 
    infor.show_toast("Thông báo", "Chương trình của bạn đã chạy xong")

In [ ]:
from SaMTPSO.learn_phase import learn_phase_task
lp= learn_phase_task() 
print(lp.operator1.name)
lp.update_operator(swap= True) 
print(lp.operator1.name)


Gauss
DE


In [ ]:
push_notification()

In [ ]:
from notification_push import * 
balloon_tip("hmmm", "hmm")

In [ ]:
from plyer import notification

notification.notify(
    title='Here is the title',
    message='Here is the message',
    app_icon=None,  # e.g. 'C:\\icon_32x32.ico'
    timeout=10,  # seconds
)

In [ ]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
srtk = np.sum(a, axis = 1) / (np.sum(a, axis = 1) + np.sum(b, axis= 1) + 0.001) 
p = srtk / np.sum(srtk) 
print(p)

[0.33332083 0.3333375  0.33334167]


In [ ]:
a = True 
a = not a 
a

False