In [1]:
import numpy as np 
a = np.ones(shape= (3, 3), dtype= int) 
a[:,1] = 0
a

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [4]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
np.random.shuffle(a)
print(a[:int(len(a)/2)])

[2, 8, 1, 3]


In [2]:
from utils.utils_model_mfea import * 

print(find_individual_same_skill_ontop([1, 1, 1, 1, 0], [1, 0.5, 0.75, 0.25, 1], 2))

1


In [3]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8])
b = np.where(a > 4)
# np.where(a[a] < 8)
print(a[b])
np.where(a[b] < 8, b, None)

[5 6 7 8]


array([[4, 5, 6, None]], dtype=object)

In [4]:
balloon_tip("aa", "aa")

NameError: name 'balloon_tip' is not defined

In [ ]:
import numpy as np 

x = [1.0, 1.0, 0.5, 0.3, 1.0]
y = [1, 2, 1, 2, 3]

print(list(set(np.where(np.array(x) == 1)[0])&set(np.where(np.array(y) == 1)[0])))

print(np.

In [ ]:
class test():

    def __init__(self):
        self.arr = []
        pass
    def append(self, val):
        self.arr.append(val)

In [ ]:
mem = [test() for i in range(3)]

In [ ]:
mem[0].append(3)
mem[0].arr

In [ ]:
[mem[i].arr for i in range(3)]

In [ ]:


def push_notification(title= "Thông báo", content = "Chương trình của bạn đã xong"):
    from win10toast import ToastNotifier
    infor = ToastNotifier() 
    infor.show_toast("Thông báo", "Chương trình của bạn đã chạy xong")

In [2]:
from SaMTPSO.learn_phase import learn_phase_task
lp= learn_phase_task() 
print(lp.operator1.name)
lp.update_operator(swap= True) 
print(lp.operator1.name)


Gauss
DE


In [ ]:
push_notification()

In [ ]:
from notification_push import * 
balloon_tip("hmmm", "hmm")

In [ ]:
from plyer import notification

notification.notify(
    title='Here is the title',
    message='Here is the message',
    app_icon=None,  # e.g. 'C:\\icon_32x32.ico'
    timeout=10,  # seconds
)

In [ ]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
srtk = np.sum(a, axis = 1) / (np.sum(a, axis = 1) + np.sum(b, axis= 1) + 0.001) 
p = srtk / np.sum(srtk) 
print(p)

[0.33332083 0.3333375  0.33334167]


In [ ]:
a = True 
a = not a 
a

False